version: v2
budget: ai2/oe-training
description: Training AOLMo
retry:
  allowedTaskRetries: 2
tasks:
  - name: train-aolmo
    image:
      beaker: ai2/cuda11.8-ubuntu20.04
    command:
      - /bin/bash
      - -c
      - /myfiles/amanr/LLaMA-Omni/beaker.sh
    datasets:
      - mountPath: /myfiles
        source:
          weka: oe-training-default
    resources:
      gpuCount: 8
    context:
      preemptible: false
      priority: normal
    constraints:
      cluster: [ai2/jupiter-cirrascale-2, ai2/ceres-cirrascale, ai2/quarantine-a]