version: v2
budget: ai2/oe-adapt
description: Merge model
retry:
  allowedTaskRetries: 1
tasks:
  - name: whole-fowl-ckhfje
    image:
      beaker: ai2/cuda11.8-ubuntu20.04
    command:
      - /bin/bash
      - -c
      - /data/input/amanr/LLaMA-Omni/beaker.sh
    datasets:
      - mountPath: /data/input
        source:
          weka: oe-training-default
    resources:
      gpuCount: 4
    context:
      preemptible: false
      priority: normal
    constraints:
      cluster: [ai2/jupiter-cirrascale-2, ai2/ceres-cirrascale, ai2/quarantine-a]
